### PR TITLE
Slimmer docker image

### PR DESCRIPTION
**Pull request by ocefpaf**
@lwasser don't merge this before testing it first with your workflow! There are some big changes here:

- unpin most software to let the solver get the latest available versions. If any software are needed at a particular version we should re-pin them, but we should avoid pins to "make the env work;"
- removed the debian build tools and the step that builds R packages. Everything is pre-built and installed with conda (makes the image creation faster, the final smaller, and the workflow easier to manage);
- reduced the number of layers in the docker image by making a singe install layer.

This last one has the advantage of a smaller and simpler docker image but having the separate `environment.yaml` may be beneficial if you point users to it so they can re-create the docker environment locally. If that is the case you may want to rever that last change.

PS0: some of the changes here are inspired by [this blog post](https://jcrist.github.io/conda-docker-tips.html) on how to reduce the docker image size when using conda.

PS1: the image went from 3.5 GB to 2.84GB and 21 to 8 layers.

### CODE REVIEW

**Comment by lwasser** [comment]
wow - ok @ocefpaf we will do some testing with this PR to figure out if things still build. Thank you again.

Question -- so i see at the top many of the base libraries were removed such as `libgdal-dev` 
It is my understanding (and know i'm still trying to understand how these libraries interact with the packages) that those libraries are required to support some of the R packages and such. Does your statement "everything is prebuild with conda"  mean that conda handles those dependencies when installed the way you have things installed here in one "layer"?

This is a really significant file size reduction!

**Comment by lwasser** [comment]
one other question. some of the packages in our list - for example hydrofunctions - i didn't think existed on conda-forge. HOWEVER i see them there now. were those recently added? and just curious - in the future if i need to add a package via pip because it is not available via conda-forge, how would i do that? thank you again. i'm so appreciative of your help.

**Comment by ocefpaf** [comment]
> Question -- so i see at the top many of the base libraries were removed such as `libgdal-dev`
> It is my understanding (and know i'm still trying to understand how these libraries interact with the packages) that those libraries are required to support some of the R packages and such. Does your statement "everything is prebuild with conda" mean that conda handles those dependencies when installed the way you have things installed here in one "layer"?

Yep. That is exactly it. Conda has its "libgdal" and all of its depencies already, bu building the R packages with the system packages you had to (probably inconsistent) copies of them. If you want to use R and Python together it is probably better to have them all built the same way.
 
> This is a really significant file size reduction!

Most of it is the removal of the build tools and duplicate dependencies from the system.

**Comment by lwasser** [comment]
this makes a lot of sense @ocefpaf thank you. We actually had a lot of issues getting R to find libgdal and some of the other libraries. i think now i am understanding this a lot more - why things weren't installing and being found properly. We ended up installing R first to make things work. we are testing things out today. Again - so appreciative.

**Comment by jvtcl** [comment]
Hi @ocefpaf, I also wanted to say thanks for all your work on this! 

I've been testing building your image locally. The build is successful but I noticed a couple of problems with loading some of the installed R packages. 

1. When I load `gridExtra` I get a bunch of warnings related to loading `sp`: 

Screen Shot 2019-07-01 at 11 46 14 AM

I don't recall seeing these warnings in previous container builds. We also never previously installed the package `codetools` ourselves. 

2. Loading `rgdal` results in an error. It looks like `libproj` might now be missing?

Screen Shot 2019-07-01 at 11 46 35 AM
 
3. The package `RSAGA` is missing from this build. I hadn't seen it previously on the conda-forge feedstocks but it appears to be there now: 

https://github.com/conda-forge/r-rsaga-feedstock

**Comment by ocefpaf** [comment]
> 1. When I load `gridExtra` I get a bunch of warnings related to loading `sp`:
> I don't recall seeing these warnings in previous container builds. We also never previously installed the package `codetools` ourselves.

I'm not an R user but looks like `codetools` is an optional dependency. Maybe the way it was installed before it was automatically pulled. Or maybe the versions of `sp` from before and now are just different. (I unpinned most of the packages in the Dockerfile.)

Does adding codetools make it go away?

> 1. Loading `rgdal` results in an error. It looks like `libproj` might now be missing?

Nope. `libproj` is there but that **is** a problem with the package. I'll work ith upstream to fix it.

> 1. The package `RSAGA` is missing from this build. I hadn't seen it previously on the conda-forge feedstocks but it appears to be there now:

My bad. I was probably testing it before adding to the file and forgot to re-add it there.

**Comment by ocefpaf** [comment]
@jvtcl do you have an "r test" similar to the imports in https://github.com/earthlab/r-python-eds-lessons-env/blob/master/import_check.py that we can run as a test?

**Comment by lwasser** [comment]
Thank you @ocefpaf  it does look like r-saga is not on conda [via dockerhub:](https://cloud.docker.com/u/earthlab/repository/docker/earthlab/r-python-eds-lessons-env/builds/7b1a3bf9-3ca1-454d-973e-c3cb4e28256f)
```
PackagesNotFoundError: The following packages are not available from current channels:
- r-rsaga
Current channels:
- https://conda.anaconda.org/conda-forge/linux-64
- https://conda.anaconda.org/conda-forge/noarch
- https://repo.anaconda.com/pkgs/main/linux-64
- https://repo.anaconda.com/pkgs/main/noarch
- https://repo.anaconda.com/pkgs/r/linux-64
- https://repo.anaconda.com/pkgs/r/noarch
To search for alternate channels that may provide the conda package you're
looking for, navigate to
https://anaconda.org
and use the search bar at the top of the page.
Removing intermediate container 08a4c07129eb
```
We can create a script that tests loading these packages like we have for Python. i believe the original script tested the install after they were installed but i need @jvtcl to confirm whether that check actually loads the package.

**Comment by ocefpaf** [comment]
> Thank you @ocefpaf it does look like r-saga is not on conda via dockerhub:

It should be in ~20 min. I just started the build.

> We can create a script that tests loading these packages like we have for Python. i believe the original script tested the install after they were installed but i need @jvtcl to confirm whether that check actually loads the package.

Yep. It tested the install, which is also a proxy for "import." However, in the future, it would be nice to have a docker command to call python and R and test this on the built image. It would remove more layers from the final image.

**Comment by lwasser** [comment]
sure. @ocefpaf when you say a docker command, do you means something like:

`RUN Rscript test-r-imports.R`
which would mirror what we have for python?

`RUN python import_check.py`

or is there a better way to do this that would eliminate layers created.
Many thanks.

**Comment by jvtcl** [comment]
@ocefpaf yep, here is what I ran in my previous check: 

```
packages <- c("dplyr",
              "ff",
              "ggplot2",
              "ggmap",
              "gridExtra",
              "knitr",
              "maps",
              "raster",
              "rasterVis",
              "rgdal",
              "rgeos",
              "RJSONIO",
              "rmarkdown",
              "RSAGA",
              "rtweet",
              "sf",
              # 'tm',
              "stringr",
              "widyr")

lapply(packages, require, character.only = TRUE)
```

**Comment by ocefpaf** [comment]
I'm fixing rgdal upstream and then I'll rebuild with this test first before pining your to test it again. (rgdal may take the whole day though, don't wait up :grimacing:)

**Comment by ocefpaf** [comment]
> sure. @ocefpaf when you say a docker command, do you means something like:
> 
> `RUN Rscript test-r-imports.R`
> which would mirror what we have for python?
> 
> `RUN python import_check.py`

Nope. That creates layers, each `COPY` and `RUN` would be a layer, so 4 total just for the tests.

> or is there a better way to do this that would eliminate layers created.
> Many thanks.

I mean adding an entrypoint to the image and then just calling something like `docker run <myscript>`. But let's leave that for the near future and focus on getting this image working first.

**Comment by lwasser** [comment]
sounds good @ocefpaf !! thank you. i didn't know each one of those lines created a layer. gosh i'm learning a lot. thank you. we will patiently wait for rgdal to build. :)

**Comment by ocefpaf** [comment]
`rgdal` and `rsaga` are up in the channel and I was able to create an environment with the same packages locally. I added the `library_check.R` there but I recommend removing that and the python test from the Dockerfile once you have a better way to test the package installation.

**Comment by lwasser** [comment]
awesome. Dockerhub is churning away on the build now. thanks so much @ocefpaf !!!

**Comment by lwasser** [comment]
so far this PR is building nicely !! thank you again @ocefpaf !!!

**Comment by ocefpaf** [comment]
Glad it is building. Note that all the packages in there are also available on macOS and Windows, so a conda `environment.yml` file with them should create a similar scientific env on those platforms in case people do not want to use docker.

**Comment by lwasser** [comment]
got it. but if i moved this to a yml file, it would add another layer to the build, is that correct?

**Comment by ocefpaf** [comment]
> got it. but if i moved this to a yml file, it would add another layer to the build, is that correct?

Yep. If you do not have that use case in mind it is not worth it.

**Comment by ocefpaf** [comment]
BTW these are all the PRs that made this possible:

https://github.com/conda-forge/click-feedstock/pull/14
https://github.com/conda-forge/staged-recipes/pull/8654
https://github.com/conda-forge/staged-recipes/pull/8655
https://github.com/conda-forge/staged-recipes/pull/8657
https://github.com/conda-forge/geocoder-feedstock/pull/20
https://github.com/conda-forge/ratelim-feedstock/pull/3
https://github.com/conda-forge/r-rgeos-feedstock/pull/12
https://github.com/conda-forge/nbgrader-feedstock/pull/25
https://github.com/conda-forge/r-rgeos-feedstock/pull/13
https://github.com/conda-forge/nbgrader-feedstock/pull/27
https://github.com/conda-forge/r-rgdal-feedstock/pull/22
https://github.com/conda-forge/r-rgdal-feedstock/pull/23
https://github.com/conda-forge/r-rgdal-feedstock/pull/24
https://github.com/conda-forge/r-rgdal-feedstock/pull/24
https://github.com/conda-forge/r-sf-feedstock/pull/21
https://github.com/conda-forge/r-rgdal-feedstock/pull/25
https://github.com/conda-forge/r-leafem-feedstock/pull/1

I used this Dockerfile as a "stress test" for conda-forge and ended up fixing a lot of small issues. If you find anything just open an issue in the respective feedstock. That way we build once so others don't have too.

**Comment by lwasser** [comment]
phew - that is a lot of PR's @ocefpaf !! we were wondering as some of these packages didn't seem to be on conda-forge before Or we've tried to use them and had issues. THANK YOU so much for this. we are excited to test out the new build

**Comment by lwasser** [comment]
everything is building nicely now!! it turns out that a PR must push an image to latest and so we've been using that image in all of our recent builds by default (we don't specify a particular commit or tag in our pull of this envt now!). SO @ocefpaf thank you. merging this. it's blazing fast to build now and we are so appreciative of all of the help cleaning things up.

**Comment by ocefpaf** [comment]
> SO @ocefpaf thank you. merging this. it's blazing fast to build now and we are so appreciative of all of the help cleaning things up.

My pleasure. I wanted an excuse to play with Docker a little bit. (I'm writing a tutorial on reproducible envs with conda, docker, pipenv, and VMs, so I needed  reason do play with this.)

**Comment by lwasser** [comment]
> My pleasure. I wanted an excuse to play with Docker a little bit. (I'm writing a tutorial on reproducible envs with conda, docker, pipenv, and VMs, so I needed reason do play with this.)

oh nice!! well please do share that tutorial when you post it as i'd love to read it. i learned a lot through this process and also it does seem like you fixed a lot of issues through it as well so hopefully others can benefit!!

**Pull request merged**
